# Camera Calibration

Import the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import cv2 as cv
import glob

## Number of intern corners

In [5]:
pattern_size = (4,3)

objp = np.zeros((pattern_size[0]*pattern_size[1],3),np.float32) # We create a 3D point for each corner in the chessboard
objp[:,:2] = np.mgrid[0:pattern_size[0],0:pattern_size[1]].T.reshape(-1,2) # We fill the 3D points with the 2D points of the chessboard


# Arrays to store the object points and image points from all the images
objpoints = [] # 3D point in real world space
imgpoints = [] # 2D points in image plane

# Loading the images
#images = glob.glob('C:/Users/felip/OneDrive/POLIMI FORE/SEMESTRE II/ADVANCED_MEASSUREMENTS/PROGETTO/photos/calibration/*.png')
images = glob.glob('C:/Users/felip/OneDrive/POLIMI FORE/SEMESTRE II/ADVANCED_MEASSUREMENTS/PROGETTO/images/calibrationCamera/*.png')

print(f"Número de imágenes encontradas: {len(images)}")

for fname in images:
    img = cv.imread(fname, 0) # We read the image in B/W
    
    ret, corners = cv.findChessboardCorners(img, pattern_size, None) # We search for the chessboard corners

    if ret == True:
        #print(f"Esquinas detectadas en {fname}")
        objpoints.append(objp)
        imgpoints.append(corners)

        cv.drawChessboardCorners(img, pattern_size, corners, ret) # We draw the chessboard corners
        cv.imshow('Esquinas detectadas', img) # We show the found corners in the image
        cv.waitKey(500)
    else:
        print(f"No se detectaron esquinas en {fname}")
cv.destroyAllWindows()


ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, img.shape[::-1], None, None)

print("Matriz de la cámara:\n", mtx)
print("Coeficientes de distorsión:\n", dist)


np.savez('calibracion_cam.npz', mtx=mtx, dist=dist, rvecs=rvecs, tvecs=tvecs)

Número de imágenes encontradas: 20
No se detectaron esquinas en C:/Users/felip/OneDrive/POLIMI FORE/SEMESTRE II/ADVANCED_MEASSUREMENTS/PROGETTO/images/calibrationCamera\img2.png
Matriz de la cámara:
 [[2.21323458e+03 0.00000000e+00 9.78757981e+02]
 [0.00000000e+00 2.21353499e+03 6.29305699e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Coeficientes de distorsión:
 [[-1.25045150e-01  6.72672547e-01  1.30287312e-05  1.08249958e-03
  -1.16896201e+00]]
